{% set sdk_version = "5.0.403" %}
{% set runtime_version = "5.0.12" %}
{% set sha256 = "bea1cc68d44ef057365a4c4166e80ef6a94a0a2face450c3f9d8a63df2d6cd83" %}  # [aarch64]
{% set sha256 = "62f2634d249f8cf62b1855e12905fd36def453c2af907c5e38fba00a20059d50" %}  # [linux]
{% set sha256 = "a3d7bd454882ab97d6de7278adbea08e4a13af2501a3ababa5ef3fb71ef278ce" %}  # [osx]
{% set sha256 = "ecbde10fbffe7d8db92482dd62bb45291ce0c5566e3d4203684cfec121bd3527" %}  # [win]
{% set platform = "linux-arm64" %}    # [aarch64]
{% set platform = "linux-x64" %}  # [linux]
{% set platform = "osx-x64" %}    # [osx]
{% set platform = "win-x64" %}    # [win]
{% set ext = "tar.gz" %}      # [not win]
{% set ext = "zip" %}         # [win]

package:
  name: dotnet
  version: {{ sdk_version }}

source:
  url: https://dotnetcli.azureedge.net/dotnet/Sdk/{{ sdk_version }}/dotnet-sdk-{{ sdk_version }}-{{ platform }}.{{ ext }}
  sha256: {{ sha256 }}
  folder: dotnet

build:
  number: 0 

outputs:
  - name: dotnet
    version: {{ sdk_version }}
    requirements:
      run:
        - {{ pin_subpackage('dotnet-runtime', exact=True) }}
        - {{ pin_subpackage('dotnet-aspnetcore', exact=True) }}
        - {{ pin_subpackage('dotnet-desktop', exact=True) }}  # [win]
        - {{ pin_subpackage('dotnet-sdk', exact=True) }}
    test:
      commands:
       - dotnet --version

  - name: dotnet-runtime
    version: {{ runtime_version }}
    script: build-runtime.bat       # [win]
    script: build-runtime.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
    test:
      commands:
        - dotnet --list-runtimes
    about:
      home: https://github.com/dotnet/runtime
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-sdk
    version: {{ sdk_version }}
    script: build-sdk.bat       # [win]
    script: build-sdk.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust             # [linux64]
        - libcurl               # [unix]
        - icu                   # [unix]
        - krb5                  # [unix]
        - __glibc >=2.17        # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - dotnet --version                   # [not aarch64]
        - test -f $PREFIX/lib/dotnet/dotnet  # [aarch64]
    about:
      home: https://github.com/dotnet/sdk
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-aspnetcore
    version: {{ runtime_version }}
    script: build-aspnetcore.bat    # [win]
    script: build-aspnetcore.sh     # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - test -d $PREFIX/lib/dotnet/shared/Microsoft.AspNetCore.App              # [not win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.AspNetCore.App exit 1  # [win]
    about:
      home: https://github.com/dotnet/aspnetcore
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-desktop                                                              # [win]
    version: {{ runtime_version }}                                                    # [win]
    script: build-desktop.bat                                                         # [win]
    requirements:                                                                     # [win]
      build:                                                                          # [win]
        - posix                                                                       # [win]
      run:                                                                            # [win]
        - dotnet-runtime ={{ runtime_version }}                                       # [win]
    test:                                                                             # [win]
      commands:                                                                       # [win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.WindowsDesktop.App exit 1  # [win]
    about:                                                                            # [win]
      home: https://github.com/dotnet/desktop                                         # [win]
      license: MIT                                                                    # [win]
      license_file: dotnet/LICENSE.txt                                                # [win]
      summary: |                                                                      # [win]
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

about:
  home: https://github.com/dotnet/core
  license: MIT
  license_file: dotnet/LICENSE.txt
  summary: |
    .NET Core is a free and open-source managed computer software
    framework for the Windows, Linux, and macOS operating systems.

extra:
  recipe-maintainers:
    - dhirschfeld
    - ZimmerA
    - acesnik
